version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0
  db:
    image: postgres:14-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    ports:
      - 5432:5432

